apiVersion: v2
appVersion: 2.2.1
description: A Helm chart for Ambassador Edge Stack
name: edge-stack
version: 7.3.1
# TODO: change these to whatever the appropriate things are
icon: https://www.getambassador.io/images/logo.png
home: https://www.getambassador.io/
sources:
- https://github.com/datawire/ambassador
- https://github.com/prometheus/statsd_exporter
keywords:
- api gateway
- ambassador
- datawire
- envoy
- edge stack
maintainers:
- name: flydiverny
  email: markus@maga.se
- name: kflynn
  email: flynn@datawire.io
- name: nbkrause
  email: nkrause@datawire.io
- name: lukeshu
  email: lukeshu@datawire.io
engine: gotpl
dependencies:
- name: emissary-ingress
  version: 7.3.1
  repository: https://s3.amazonaws.com/datawire-static-files/charts
